function tableout = importfile10(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE10 Import data from a spreadsheet
%   DATA = IMPORTFILE10(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   table.
%
%   DATA = IMPORTFILE10(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE10(FILE,SHEET,STARTROW,ENDROW) reads from the
%   specified worksheet for the specified row interval(s). Specify STARTROW
%   and ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   RECHTRUE = importfile10('RE_CH_TRUE.xlsx','Sheet 1',15,114);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2019/04/09 12:11:05

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 15;
    endRow = 114;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('B%d:B%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('B%d:B%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Create table
tableout = table;

%% Allocate imported array to column variable names
tableout.Close = data(:,1);

