function [FTSE100IndexPriceHistoryThomsonReutersEikon101605Apr2019,VarName2] = importfile3(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE3 Import data from a spreadsheet
%   [FTSE100IndexPriceHistoryThomsonReutersEikon101605Apr2019,VarName2] =
%   IMPORTFILE3(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [FTSE100IndexPriceHistoryThomsonReutersEikon101605Apr2019,VarName2] =
%   IMPORTFILE3(FILE,SHEET) reads from the specified worksheet.
%
%   [FTSE100IndexPriceHistoryThomsonReutersEikon101605Apr2019,VarName2] =
%   IMPORTFILE3(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [FTSE100IndexPriceHistoryThomsonReutersEikon101605Apr2019,VarName2] = importfile3('FTSE_monthly .xlsx','Sheet 1',24,123);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2019/04/06 13:22:15

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 24;
    endRow = 123;
end

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread(workbookFile, sheetName, sprintf('A%d:B%d',startRow(1),endRow(1)),'' , @convertSpreadsheetExcelDates);
for block=2:length(startRow)
    [~, ~, tmpRawBlock,tmpDateNumBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:B%d',startRow(block),endRow(block)),'' , @convertSpreadsheetExcelDates);
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
    dates = [dates;tmpDateNumBlock]; %#ok<AGROW>
end
raw = raw(:,2);
dates = dates(:,1);

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
dates(~cellfun(@(x) isnumeric(x) || islogical(x), dates)) = {NaN};
FTSE100IndexPriceHistoryThomsonReutersEikon101605Apr2019 = datetime([dates{:,1}].', 'ConvertFrom', 'Excel');
VarName2 = data(:,1);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% FTSE100IndexPriceHistoryThomsonReutersEikon101605Apr2019=datenum(FTSE100IndexPriceHistoryThomsonReutersEikon101605Apr2019);

