function [Dates,SMIMCIndex,SPTR500NIndex,CACRIndex,TUKXGIndex,LD08TRUUIndex,SBIDGTIndex,RE_UK1,RE_FR1,RE_ASIA,RE_US1,RE_Listed_CH,DIRECT_RE_CH] = importfile1(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE1 Import data from a spreadsheet
%   [Dates,SMIMCIndex,SPTR500NIndex,CACRIndex,TUKXGIndex,LD08TRUUIndex,SBIDGTIndex,RE_UK1,RE_FR1,RE_ASIA,RE_US1,RE_Listed_CH,DIRECT_RE_CH]
%   = IMPORTFILE1(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as
%   column vectors.
%
%   [Dates,SMIMCIndex,SPTR500NIndex,CACRIndex,TUKXGIndex,LD08TRUUIndex,SBIDGTIndex,RE_UK1,RE_FR1,RE_ASIA,RE_US1,RE_Listed_CH,DIRECT_RE_CH]
%   = IMPORTFILE1(FILE,SHEET) reads from the specified worksheet.
%
%   [Dates,SMIMCIndex,SPTR500NIndex,CACRIndex,TUKXGIndex,LD08TRUUIndex,SBIDGTIndex,RE_UK1,RE_FR1,RE_ASIA,RE_US1,RE_Listed_CH,DIRECT_RE_CH]
%   = IMPORTFILE1(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   [Dates,SMIMCIndex,SPTR500NIndex,CACRIndex,TUKXGIndex,LD08TRUUIndex,SBIDGTIndex,RE_UK1,RE_FR1,RE_ASIA,RE_US1,RE_Listed_CH,DIRECT_RE_CH] = importfile1('DATA_Total_Returns.xlsx','Feuil1',1,83);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2019/05/12 13:15:28

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 83;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:M%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:M%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Dates = data(:,1);
SMIMCIndex = data(:,2);
SPTR500NIndex = data(:,3);
CACRIndex = data(:,4);
TUKXGIndex = data(:,5);
LD08TRUUIndex = data(:,6);
SBIDGTIndex = data(:,7);
RE_UK1 = data(:,8);
RE_FR1 = data(:,9);
RE_ASIA = data(:,10);
RE_US1 = data(:,11);
RE_Listed_CH = data(:,12);
DIRECT_RE_CH = data(:,13);

